# Local Cassandra
spring:
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      keyspace-name: ecommercekeyspace
      entity-base-package: ankitiit.springboot.cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1


# Azure Cosmos Cassandra -API
#spring:
#  data:
#    cassandra:
#      contact-points: ankitiit-database.cassandra.cosmos.azure.com
#      port: 10350
#      keyspace-name: schoolkeyspace
#      entity-base-package: ankitiit.springboot.cassandra.dto
#      username : ankitiit-database
#      password : uYd031G6IM6L6q6JP80xZSV2kgDF6UBDS3gyDalzA7sJfxZpzpJquUgPrGrqK4Rpn7u4RdDm3XZh7ALNJmvp4A==
#      ssl : true
#      #local-datacenter: westus